# Generated by Django 5.0 on 2023-12-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Set category',
                'verbose_name_plural': 'Set categories',
            },
        ),
    ]
