# Generated by Django 5.0 on 2023-12-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_library', '0003_set_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_category', to='community_library.setcategory'),
        ),
    ]
