# Generated by Django 5.0 on 2023-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_description', models.CharField(max_length=100)),
                ('feature_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('advantages', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=100)),
            ],
        ),
    ]
