# Generated by Django 5.0 on 2023-12-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending_page', '0002_remove_lending_advantages_remove_lending_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantages', models.CharField(max_length=100, null=True)),
                ('advantage_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('feature_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
